influxdb:
  image: influxdb:1.2.4
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'

telegraf:
  image: telegraf:1.3.5
  container_name: telegraf
  ports:
    - "8125/udp:8125/udp"
  links:
    - influxdb
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

grafana:
  image: grafana/grafana:4.4.3
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
